---
title: "Gafo-cc data processing"
output: html_document
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(prettyR) # for describe()
library(jsonlite) # for reading in json files
library(stringr)
library(eeptools)
library(lubridate) # for date handling
library(readxl)
library(readODS)
library(truncnorm)

options(scipen = 999)
theme_set(theme_classic())
```

# Namibia

```{r read_data}
# get all .json files
files <- list.files("../../raw_data/gafo-cc/namibia/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_namibia <- tibble()
for (f in files) {
  jf <- paste("../../raw_data/gafo-cc/namibia/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_namibia <- bind_rows(raw_data_namibia, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_namibia <- raw_data_namibia %>%
  
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali"), 
  ) %>%
  mutate(subjID = toupper(subjID))%>%select(-touchScreen)#%>% select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)

```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_namibia$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_namibia%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```


```{r demographics}
raw_demographics_namibia <- bind_rows(
  read_xlsx("../../raw_data/gafo-cc/namibia/Data Haikom 2022.xlsx", sheet = 1, col_types = c("numeric", "text", "text", "text", "date", "date", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "text"))%>%mutate(ID = paste0("H",str_pad(ID, 7, pad = "0")))%>%mutate(site = Community, Community = "hai||om"),
  read_xlsx("../../raw_data/gafo-cc/namibia/Data Khwe 2022.xlsx", sheet = 1, col_types = c("numeric", "text", "text", "text", "date", "date", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "text"))%>%mutate(ID = paste0("K",str_pad(ID, 7, pad = "0")))%>%rename(Sex = `...7`)%>%mutate(site = Community, Community = "khwe"),
    read_xlsx("../../raw_data/gafo-cc/namibia/Data Windhoek 2022 completed.xlsx", sheet = 1)%>%
    select(ID, Community,`First Name`,Name,	BirthDate,	TestDate,	Sex,	Screen,	Touchscreen,	Household,	Children,	YoungerChildren)%>%mutate(ID = paste0("W",str_pad(ID, 7, pad = "0")))%>%mutate(site = Community, Community = "windhoek")
  )%>%
  filter(!grepl("rop",Comment))

testdates <- tidy_data_namibia%>%
  select(subjID, timestamp)%>%
  mutate(test_date = as.Date(substr(timestamp, 0,10)))%>%
  select(subjID, test_date)%>%
  distinct(subjID, .keep_all = T)%>%
  mutate(subjID = toupper(subjID))

tidy_demographics_namibia <- raw_demographics_namibia %>% 
  rename(subjID = ID)%>%
  left_join(testdates)%>%
  mutate(
    ageInYears = as.numeric(difftime(test_date,BirthDate, units = "days")/365.25),
    Children = ifelse(subjID == "W0000023", 2, Children)
  ) %>%
  select(-c(`First Name`, Name, BirthDate, TestDate,test_date, Comment))%>% 
  rename_all(tolower)%>%
  filter(!is.na(ageinyears))
  
```

```{r}
# quality checks

# check for typos in subject names, is there a data file for every child in the demographics spreadsheet?
tidy_demographics_namibia%>%
  filter(!subjid %in% tidy_data_namibia$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_namibia$ageinyears) 

# screen and touchscreen should only be 0 or 1 
unique(tidy_demographics_namibia$screen) 
unique(tidy_demographics_namibia$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_namibia%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_namibia%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_namibia%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_namibia%>%filter(youngerchildren >= children) 


exclude_namib <- tidy_demographics_namibia%>%filter(children >= household) %>% pull(subjid)

```


```{r}
data_namibia <- tidy_demographics_namibia%>%
  left_join(tidy_data_namibia%>%rename_all(tolower),by = c("subjid"))%>%
  filter(!subjid %in% exclude_namib)%>%
  distinct(subjid, trialnr, .keep_all = T)

```

```{r}
# did a child get lost on the way?
n_distinct(tidy_demographics_namibia$subjid) == (n_distinct(data_namibia$subjid) + length(exclude_namib))
```


# Leipzig

```{r}
system("rsync -zaP ccp-odcJ:/srv/ccp-odc/gafo-leipzig/data/ ~/Work/Local/QuantEx/Gafo/raw_data/gafo-cc/leipzig/")
```


```{r read_data}
# get all .json files
files <- list.files("../../raw_data/gafo-cc/leipzig/", pattern = "*.json",recursive = T)%>% str_subset(pattern = "gafo--", negate = T)

# convert json files to tibbles
raw_data_leipzig <- tibble()
for (f in files) {
  jf <- paste("../../raw_data/gafo-cc/leipzig/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_leipzig <- bind_rows(raw_data_leipzig, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_leipzig <- raw_data_leipzig %>%
  
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali"), 
  ) %>%
  mutate(subjID = as.character(subjID),
         subjID = ifelse(subjID == "VcyYgGQx", "VcyYgFQx", subjID),
         subjID = ifelse(subjID == "R9V7qHrx", "R9v7qHrx", subjID),
         subjID = ifelse(subjID == "QZJvSwfQ","QZJvSwftQ",  subjID),
         subjID = ifelse(subjID == "TSPeVFYf", "tSPeVFYf", subjID),
         subjID =as.factor(subjID))%>%select(-touchScreen)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)


#unique(tidy_data_leipzig$subjID)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_leipzig$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_leipzig%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r demographics}
raw_demographics_leipzig <- bind_rows(
  read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/docs/Gafo-cc-leipzig-participants.xlsx", sheet = 1)
  #read_xlsx("../../raw_data/gafo-cc/leipzig/Gafo-cc-leipzig-participants.xlsx", sheet = 1)
  )%>%
  mutate(status = ifelse(code == "o9qVPfZD", "keep", status))

tidy_demographics_leipzig <- raw_demographics_leipzig %>% 
  mutate(
    test_date = as.Date(test_date, format = "%d/%m/%Y"),
    birth_date = as.Date(birth_date, format = "%d.%m.%Y"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
    sex = ifelse(sex == "w", "f", sex)
  ) %>%
  select(-c(first_name, last_name, id, test_date, birth_date))%>%
  rename(subjid = code)%>%
  filter(status == "keep")
```


```{r}
# quality checks

# check for typos in subject names
tidy_demographics_leipzig%>%
  filter(!subjid %in% tidy_data_leipzig$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_leipzig$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_leipzig$screen) 
unique(tidy_demographics_leipzig$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_leipzig%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_leipzig%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_leipzig%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_leipzig%>%filter(younger_children >= children) 
```


```{r}
data_leipzig <- tidy_demographics_leipzig%>%
  left_join(tidy_data_leipzig%>%rename_all(tolower),by = c("subjid"))%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```

```{r}
# did a child get lost on the way?
n_distinct(tidy_demographics_leipzig$subjid) <= (n_distinct(tidy_data_leipzig$subjID))
```

# Nigeria

```{r read_data}
# get all .json files
files <- list.files("../../../../../../Cloud/QuantEx/Gafo-cc/data/nigeria/JSONs/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_nigeria <- tibble()
for (f in files) {
  jf <- paste("../../../../../../Cloud/QuantEx/Gafo-cc/data/nigeria/JSONs/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_nigeria <- bind_rows(raw_data_nigeria, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_nigeria <- raw_data_nigeria %>%
  
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali"),
    subjID = as.character(subjID),
    subjID = ifelse(subjID == "nlger002", "niger002", subjID)
  ) %>%select(-touchScreen)#%>% select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_nigeria$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_nigeria%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r demographics}
raw_demographics_nigeria <- bind_rows(
  read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/data/nigeria/gafo-cc-nigeria-participants.xlsx", sheet = 1)
  )

tidy_demographics_nigeria <- raw_demographics_nigeria %>% 
  filter(community!= "leipzig")%>%
  mutate(
    birth_date = ifelse(birth_date == "10.11.1016", "10.11.2016", birth_date),
    test_date = as.Date(test_date, format = "%d.%m.%Y"),
    birth_date = as.Date(birth_date, format = "%d.%m.%Y"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
  )  %>%
  select(-c(first_name, last_name, test_date, birth_date, `...14`, `...15`, comment))%>%
  rename(subjid = id)%>%
  filter(!is.na(ageinyears))
```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_nigeria%>%
  filter(!subjid %in% tidy_data_nigeria$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_nigeria$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_nigeria$screen) 
unique(tidy_demographics_nigeria$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_nigeria%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_nigeria%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_nigeria%>%filter(children >= household) 
# younger children should be fewer than children
tidy_demographics_nigeria%>%filter(younger_children >= children) 

exclude_niger <- tidy_demographics_nigeria%>%filter(younger_children >= children) %>% pull(subjid)
```

```{r}
data_nigeria <- tidy_demographics_nigeria%>%
  left_join(tidy_data_nigeria%>%rename_all(tolower),by = c("subjid"))%>%
  filter(!subjid %in% exclude_niger)%>%
  mutate(location = community,
         community = "akure")%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```


```{r}
# did a child get lost on the way?
n_distinct(tidy_demographics_nigeria$subjid) == (n_distinct(data_nigeria$subjid) + length(exclude_niger))
```

# Zambia

```{r read_data}
# get all .json files
files <- list.files("../../raw_data/gafo-cc/zambia/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_zambia <- tibble()
for (f in files) {
  jf <- paste("../../raw_data/gafo-cc/zambia/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_zambia <- bind_rows(raw_data_zambia, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_zambia <- raw_data_zambia %>%
  
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali"),
    subjID = paste0("z", subjID),
  ) %>%select(-touchScreen)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_zambia$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_zambia%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```


```{r demographics}
raw_demographics_zambia <- bind_rows(
  read_xlsx("../../raw_data/gafo-cc/zambia/Gafo_cc_Zambia_April23_Final.xlsx", sheet = 1)
  )

tidy_demographics_zambia <- raw_demographics_zambia %>% 
  filter(community!= "leipzig")%>%
  mutate(
    #test_date = as.Date(test_date, format = "%d/%m/%Y"),
    #birth_date = as.Date(birth_date, format = "%d/%m/%Y"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
    id = paste0("z", id),
    screen = ifelse(screen == "yes", 1, 0),
    touchscreen = ifelse(touchscreen == "yes", 1, 0)
  )  %>%
  filter(status == "keep")%>%
  select(-c(test_date, birth_date, comment, Age, consent_signed, Nr, status))%>%
  rename(subjid = id)%>%
  filter(!is.na(ageinyears))
```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_zambia%>%
  filter(!subjid %in% tidy_data_zambia$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_zambia$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_zambia$screen) 
unique(tidy_demographics_zambia$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_zambia%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_zambia%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_zambia%>%filter(children >= household) 
# younger children should be fewer than children
tidy_demographics_zambia%>%filter(younger_children >= children) 
```

```{r}
data_zambia <- tidy_demographics_zambia%>%
  left_join(tidy_data_zambia%>%rename_all(tolower),by = c("subjid"))%>%
  mutate(community = "chimfunshi")%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```


```{r}
# did a child get lost on the way?
n_distinct(tidy_demographics_zambia$subjid) <= (n_distinct(data_zambia$subjid))
```

# Stanford

```{r}
raw_data_stanford <- read.csv("../../raw_data/gafo-cc/stanford/tidy_data_extra.csv")%>%
  mutate(subjID = paste0("S",subjID),
         community = "stanford",
         screen = ifelse(screen == "yes", 1, 0),
         touchscreen = ifelse(touchscreen == "yes", 1, 0),
         browserVersion = factor(browserVersion),
         targetPosition = factor(targetPosition))%>%
  select(-touchScreen)%>%
  rename(ageinyears = age)%>%
  rename_all(tolower)%>%
  distinct(subjid, trialnr, .keep_all = T)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(raw_data_stanford$clickdistfromtargetcenterx)) # 

# number of trials: everyone should have more than 4 trials.
raw_data_stanford%>%group_by(subjid)%>%filter(voiceover == F, trialtype == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r}
# quality checks

# range of ages: should not be below 2.5
range(raw_data_stanford$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(raw_data_stanford$screen) 
unique(raw_data_stanford$touchscreen) 

# children should at least be 1 (the tested child) 
raw_data_stanford%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
raw_data_stanford%>%filter(household < 2) 
# household should be larger than children
raw_data_stanford%>%filter(children >= household) 
# youngerchildren should be fewer than children
raw_data_stanford%>%filter(younger_children >= children) 

exclude_stanf <- raw_data_stanford%>%filter(children >= household)%>%distinct(subjid)%>%pull(subjid)
```

```{r}
data_stanford <- raw_data_stanford%>%
  filter(!subjid %in% exclude_stanf)
```

# Plymouth

```{r}
system("rsync -zaP ccp-odcJ:/srv/ccp-odc/gafo-uk/data/ ~/Work/Local/QuantEx/Gafo/raw_data/gafo-cc/plymouth/")
```

```{r read_data}
# get all .json files
files <- list.files("../../raw_data/gafo-cc/plymouth/", pattern = "*.json",recursive = T)%>% str_subset(pattern = "gafo--", negate = T)

# convert json files to tibbles
raw_data_plymouth <- tibble()
for (f in files) {
  jf <- paste("../../raw_data/gafo-cc/plymouth/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_plymouth <- bind_rows(raw_data_plymouth, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_plymouth <- raw_data_plymouth %>%
  
  # convert all character vectors into factors
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali")
  ) %>%
  mutate(subjID = ifelse(grepl("2023-03-11T19:4", timestamp) & subjID == "uksch048", "uksch049", subjID),
         subjID = ifelse(subjID == "Uksch002", "uksch002", subjID),
         subjID = ifelse(subjID == "Uksch003", "uksch003", subjID))%>%
  mutate(subjID =as.factor(subjID))%>%
  select(-touchScreen)%>%
  mutate_if(is.character, as.factor)%>% 
  distinct(subjID, trialNr, .keep_all = T)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_plymouth$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_plymouth%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r demographics}
raw_demographics_plymouth <- bind_rows(
  read_xlsx("../../raw_data/gafo-cc/plymouth/participants_information_updated_2023_May.xlsx", sheet = 1)
  )%>%
  filter(tested == "yes", subjid != "uksch057")

test_date_plymouth <- tidy_data_plymouth%>%
  select(subjID, timestamp)%>%
  mutate(test_date = as.Date(substr(timestamp, 1,10),format = "%Y-%m-%d"))%>%
  select(-timestamp)%>%
  rename_all(tolower)%>%
  distinct(subjid, test_date)

tidy_demographics_plymouth <- raw_demographics_plymouth %>% 
  #select(-test_date)%>%
  #left_join(test_date_plymouth)%>%
  mutate(
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
    younger_children = ifelse(younger_children == "N/A", NA, younger_children),
    younger_children = as.numeric(younger_children)
  )  %>%
  select(-c(test_date, birth_date, comment))%>%
  filter(!is.na(ageinyears))

```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_plymouth%>%
  filter(!subjid %in% tidy_data_plymouth$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_plymouth$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_plymouth$screen) 
unique(tidy_demographics_plymouth$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_plymouth%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_plymouth%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_plymouth%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_plymouth%>%filter(younger_children >= children) 
```

```{r}
data_plymouth <- tidy_demographics_plymouth%>%
  left_join(tidy_data_plymouth%>%rename_all(tolower),by = c("subjid"))%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```


# Mexico

```{r read_data}
# get all .json files
files <- list.files("../../../../../../Cloud/QuantEx/Gafo-cc/data/mexico/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_mex <- tibble()
for (f in files) {
  jf <- paste("../../../../../../Cloud/QuantEx/Gafo-cc/data/mexico/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_mex <- bind_rows(raw_data_mex, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_mex <- raw_data_mex %>%
  
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali")
  ) %>%select(-touchScreen)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_mex$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_mex%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r demographics}
raw_demographics_mex <- bind_rows(
  read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/data/mexico/participants.xlsx", sheet = 1)
  )%>%
  filter(!is.na(lastname))%>%
  mutate(birth_date = ifelse(birth_date == 29042017, 20170429, birth_date), 
         subjid = ifelse(subjid == "Mexva37", "Mexva037", subjid),
         subjid = ifelse(subjid == "Mexva51", "Mexva051", subjid), 
         children = ifelse(subjid == "Mexli040", children + 1, children),
         children = ifelse(subjid == "Mexli064", children + 1, children))

tidy_demographics_mex <- raw_demographics_mex %>% 
  mutate(
    
    test_date = as.Date(as.character(test_date), format = "%Y%m%d"),
    birth_date = as.Date(as.character(birth_date), format = "%Y%m%d"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
  )  %>%
  select(-c(name, lastname, test_date, birth_date, comment))%>%
  filter(!is.na(ageinyears))%>%
  mutate(household = household + children)

```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_mex%>%
  filter(!subjid %in% tidy_data_mex$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_mex$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_mex$screen) 
unique(tidy_demographics_mex$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_mex%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_mex%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_mex%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_mex%>%filter(younger_children >= children) 
```

```{r}
data_mex <- tidy_demographics_mex%>%
  left_join(tidy_data_mex%>%rename_all(tolower),by = c("subjid"))%>%
  mutate(community = "mexico")%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```

```{r}
# data_liz <- bind_rows(data_mex%>%
#   filter(trialtype == "test", voiceover == F)%>%
#   mutate(click_distance = abs(clickdistfromtargetcenterx))%>%
#   select("subjid" ,"community" ,"ageinyears" , "trialnr", "targetposition",  "click_distance", "sex", "economical_activity_dad" , "economical_activity_mom"   ,    "parents_education_level_dad"  , "parents_education_level_mom" ,  "income" ,    "screen"           ,             "touchscreen"       ,            "household"     ,                "children" ,
#         "younger_children"),
# 
# data_leipzig%>%
#   filter(trialtype == "test", voiceover == F)%>%
#   mutate(click_distance = abs(clickdistfromtargetcenterx))%>%
#   select("subjid" ,"community" ,"ageinyears" , "trialnr", "targetposition",  "click_distance", "sex", "screen"           ,             "touchscreen"       ,            "household"     ,                "children" ,
#         "younger_children")
# )
# 
# 
#   write_csv(data_liz, "../data/gafo-cc-data-lizbeth.csv")
#   
# 
# data_liz <- read_csv("gafo-cc-data-lizbeth.csv")
# 
# 
# data_liz_agg <- data_liz%>%
#   group_by(subjid, community, ageinyears, sex, economical_activity_dad, economical_activity_mom, parents_education_level_dad, parents_education_level_mom, income, screen, touchscreen, household, children, younger_children)%>%
#   summarise(mean_distance = mean(click_distance))%>% # aggregate data to get average click distance
#   ungroup()%>%
#   mutate(mean_distance_scale = scale(mean_distance, scale = F, center = T), # make the DV so that it has a mean of 0
#          z_ageinyears = scale(ageinyears, scale = F, center = T), # scale numeric variables
#          f_income = factor(income),# convert numeric variable into a factor because different values represent different categories
#          z_household = scale(household)) 
# 
# 
# library(lme4)
# 
# m1 <- lm(mean_distance_scale ~ z_ageinyears + community, data = data_liz_agg)
# 
# drop1(m1, test = "Chisq") # to get p-values for entire factors you need to use drop1
# 
# summary(m1)
```


# China

```{r}
system("rsync -zaP ccp-odcJ:/srv/ccp-odc/gafo-china/data/ ~/Work/Local/QuantEx/Gafo/raw_data/gafo-cc/china/")
```

```{r read_data}
# get all .json files
files <- list.files("../../raw_data/gafo-cc/china/", pattern = "*.json",recursive = T)%>% str_subset(pattern = "gafo--", negate = T)

# convert json files to tibbles
raw_data_china <- tibble()
for (f in files) {
  jf <- paste("../../raw_data/gafo-cc/china/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_china <- bind_rows(raw_data_china, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_china <- raw_data_china %>%
  
  # convert all character vectors into factors
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali"), 
  ) %>%
  mutate(subjID = ifelse(grepl("2023-04-13T03:1", timestamp), "china075", subjID),
         subjID = ifelse(grepl("2023-04-13T07:0", timestamp), "china077", subjID))%>%
  select(-touchScreen)%>%
  distinct(subjID, trialNr, .keep_all = T)%>%
   mutate_if(is.character, as.factor)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)

```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_china$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_china%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r demographics}
raw_demographics_china <- bind_rows(
  read_xlsx("../../raw_data/gafo-cc/china/gafo-cc-participants_China_0608_final_updated.xlsx", sheet = 1, 
            col_types = c("text", "text", "text", "skip", "skip", "skip", "date", "date", "numeric", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "text"))
  )%>%
  filter(!row_number() == 1)

tidy_demographics_china <- raw_demographics_china %>% 
  mutate(
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25)
  )  %>%
  select(-c(test_date, birth_date, comment))%>%
  filter(status == "included", 
         !is.na(ageinyears))%>%
  select(-status)%>%
  rename(subjid = id)

```


```{r}
# quality checks

# check for typos in subject names
tidy_demographics_china%>%
  filter(!subjid %in% tidy_data_china$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_china$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_china$screen) 
unique(tidy_demographics_china$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_china%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_china%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_china%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_china%>%filter(younger_children >= children) 
```

```{r}
data_china <- tidy_demographics_china%>%
  left_join(tidy_data_china%>%rename_all(tolower),by = c("subjid"))%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```

# Argentina

```{r read_data}
# get all .json files
files <- list.files("../../../../../../Cloud/QuantEx/Gafo-cc/data/argentina/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_arg <- tibble()
for (f in files) {
  jf <- paste("../../../../../../Cloud/QuantEx/Gafo-cc/data/argentina/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_arg <- bind_rows(raw_data_arg, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_arg <- raw_data_arg %>%
  
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali"),
  ) %>%select(-touchScreen)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_arg$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_arg%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r demographics}
raw_demographics_arg <- bind_rows(
  read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/data/argentina/gafo-cc-arg-participants.xlsx", sheet = 1, 
            col_types = c("text", "text", "text", "text", "date", "date", "text", "text", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "text"))
  )

tidy_demographics_arg <- raw_demographics_arg %>% 
  filter(Status== "keep")%>%
  mutate(
    test_date = as.Date(test_date, format = "%d/%m/%Y"),
    birth_date = as.Date(birth_date, format = "%d/%m/%Y"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25)
  )  %>%
  #filter(status == "keep")%>%
  select(-c(test_date, birth_date, comment, Edad))%>%
  rename(subjid = id)%>%
  filter(!is.na(ageinyears))%>%
  mutate(touchscreen = as.numeric(touchscreen),
         household = as.numeric(household),
         children = as.numeric(children),
         younger_children = as.numeric(younger_children))

```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_arg%>%
  filter(!subjid %in% tidy_data_arg$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_arg$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_arg$screen) 
unique(tidy_demographics_arg$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_arg%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_arg%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_arg%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_arg%>%filter(younger_children >= children) 
```

```{r}
data_arg <- tidy_demographics_arg%>%
  left_join(tidy_data_arg%>%rename_all(tolower),by = c("subjid"))%>%
  mutate(community = "buenos_aires")%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```

# India

```{r read_data}
# get all .json files
files <- list.files("../../../../../../Cloud/QuantEx/Gafo-cc/data/india/Data/India_Data/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_ind <- tibble()
for (f in files) {
  jf <- paste("../../../../../../Cloud/QuantEx/Gafo-cc/data/india/Data/India_Data/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_ind <- bind_rows(raw_data_ind, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_ind <- raw_data_ind %>%
  
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali"),
  ) %>%select(-touchScreen)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_ind$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_ind%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r }
raw_demographics_ind <- read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/data/india/Gafo_Corrected.xlsx", sheet = 1)

tidy_demographics_ind <- raw_demographics_ind %>% 
  mutate(
    test_date = as.Date(as.character(test_date), format = "%Y%m%d"),
    birth_date = as.Date(as.character(birth_date), format = "%Y%m%d"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
  )  %>%
  select(-c(test_date, birth_date, comment))%>%
  filter(!is.na(ageinyears))%>%
  rename(subjid = id)

```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_ind%>%
  filter(!subjid %in% tidy_data_ind$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_ind$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_ind$screen) 
unique(tidy_demographics_ind$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_ind%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_ind%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_ind%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_ind%>%filter(younger_children >= children) 

exclude_ind <- c(tidy_demographics_ind%>%filter(children >= household) %>% pull(subjid),
                 tidy_demographics_ind%>%filter(younger_children >= children)%>% pull(subjid))
                 
```

```{r}
data_ind <- tidy_demographics_ind%>%
  filter(!subjid %in%exclude_ind)%>%
  left_join(tidy_data_ind%>%rename_all(tolower),by = c("subjid"))%>%
  mutate(community = "india")%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```

# Auckland

```{r}
system("rsync -zaP ccp-odcJ:/srv/ccp-odc/gafo-newzealand/data/ ~/Work/Local/QuantEx/Gafo/raw_data/gafo-cc/auckland/")
```

```{r read_data}
# get all .json files
files <- list.files("../../../../../../Cloud/QuantEx/Gafo-cc/data/new_zealand/data/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_nz <- tibble()
for (f in files) {
  jf <- paste("../../../../../../Cloud/QuantEx/Gafo-cc/data/new_zealand/data/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_nz <- bind_rows(raw_data_nz, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_nz <- raw_data_nz %>%
  
  # convert all character vectors into factors
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali")
  ) %>%
  mutate(subjID = ifelse(grepl("2023-03-11T19:4", timestamp) & subjID == "uksch048", "uksch049", subjID),
         subjID = ifelse(subjID == "Uksch002", "uksch002", subjID),
         subjID = ifelse(subjID == "Uksch003", "uksch003", subjID))%>%
  mutate(subjID =as.factor(subjID))%>%
  select(-touchScreen)%>%
  mutate_if(is.character, as.factor)%>% 
  distinct(subjID, trialNr, .keep_all = T)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)


unique(tidy_data_nz$subjID)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_nz$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_nz%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r demographics}
raw_demographics_nz <- bind_rows(
  read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/data/new_zealand/gafo-cc-new-zealand-participants.xlsx", sheet = 1)
  )%>%
  filter(id != "NZ000001")

tidy_demographics_nz <- raw_demographics_nz %>% 
  mutate(
    
    test_date = as.Date(as.character(test_date), format = "%Y%m%d"),
    birth_date = as.Date(as.character(birth_date), format = "%Y%m%d"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
  )  %>%
  select(-c(first_name, last_name, test_date, birth_date, comment))%>%
  filter(!is.na(ageinyears))%>%
  rename(subjid = id)

```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_nz%>%
  filter(!subjid %in% tidy_data_nz$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_leipzig$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_leipzig$screen) 
unique(tidy_demographics_leipzig$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_leipzig%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_leipzig%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_leipzig%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_leipzig%>%filter(younger_children >= children) 
```

```{r}
data_nz <- tidy_demographics_nz%>%
  left_join(tidy_data_nz%>%rename_all(tolower),by = c("subjid"))%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```

# Turkey

```{r read_data}
# get all .json files
files <- list.files("../../../../../../Cloud/QuantEx/Gafo-cc/data/turkey/data/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_tur <- tibble()
for (f in files) {
  jf <- paste("../../../../../../Cloud/QuantEx/Gafo-cc/data/turkey/data/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_tur <- bind_rows(raw_data_tur, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_tur <- raw_data_tur %>%
  
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali"),
    subjID = as.character(subjID),
    subjID = ifelse(subjID == "TUR79000", "TUR00079",subjID),
    subjID = ifelse(subjID == "TUR80000", "TUR00080",subjID),
    subjID = ifelse(subjID == "TUR81000", "TUR00081",subjID),
    subjID = ifelse(subjID == "TUR83000", "TUR00083",subjID),
    subjID = ifelse(subjID == "TUR84000", "TUR00084",subjID),
    subjID = ifelse(subjID == "TUR85000", "TUR00085",subjID)
  ) %>%select(-touchScreen)%>%
  mutate(subjID = factor(subjID))#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_tur$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_tur%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r }
raw_demographics_tur <- read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/data/turkey/gafo-cc-turkey-participants.xlsx", sheet = 1)

tidy_demographics_tur <- raw_demographics_tur %>% 
  mutate(
    test_date = as.Date(as.character(test_date), format = "%Y%m%d"),
    birth_date = as.Date(as.character(birth_date), format = "%Y%m%d"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
  )  %>%
  select(-c(first_name, last_name, test_date, birth_date, comment))%>%
  #filter(!is.na(ageinyears))%>%
  rename(subjid = id)

```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_tur%>%
  filter(!subjid %in% tidy_data_tur$subjID)

# range of ages: should not be below 2.5
range(tidy_demographics_tur$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_tur$screen) 
unique(tidy_demographics_tur$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_tur%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_tur%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_tur%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_tur%>%filter(younger_children >= children) 
```

```{r}
data_tur <- tidy_demographics_tur%>%
  left_join(tidy_data_tur%>%rename_all(tolower),by = c("subjid"))%>%
  mutate(community = "turkey")%>%
  distinct(subjid, trialnr, .keep_all = TRUE)%>%
  mutate(subjid = recode(subjid, 
                     "EBRAR100" = "TUR00001",
                     "FATMA400" = "TUR00002",
                     "ASYAA200" = "TUR00003"))
```

# Congo

```{r read_data}
# get all .json files
files <- list.files("../../../../../../Cloud/QuantEx/Gafo-cc/data/congo/data_GaFo/", pattern = "*.json",recursive = T)

# convert json files to tibbles
raw_data_cong <- tibble()
for (f in files) {
  jf <- paste("../../../../../../Cloud/QuantEx/Gafo-cc/data/congo/data_GaFo/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_cong <- bind_rows(raw_data_cong, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_cong <- raw_data_cong %>%
  mutate(subjID = ifelse(subjID == "BD000063", "BY000063", subjID))%>%
  # convert all character vectors into factors
  mutate_if(is.character, as.factor) %>% 
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali")
  ) %>%select(-touchScreen)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_cong$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_cong%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r }
raw_demographics_cong <- bind_rows(
    read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/data/congo/gafo-cc-congo-participants_2023_V3.xlsx", sheet = 1)%>%
      mutate(household = as.character(household),
             children = as.character(children),
             younger_children = as.character(younger_children)),
    read_xlsx("../../../../../../Cloud/QuantEx/Gafo-cc/data/congo/gafo-cc-congo-participants_2023_V3.xlsx", sheet = 2),
  )

tidy_demographics_cong <- raw_demographics_cong %>%
  filter(birth_date != "NA")%>%
  filter(status == "keep", id != "BD000001", id != "BY000001")%>%
  mutate(
    test_date = as.Date(as.character(test_date), format = "%Y%m%d"),
    birth_date = as.Date(as.character(birth_date), format = "%Y%m%d"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
    #screen = ifelse(screen == "fallaci", 0, 1), 
    #touchscreen = ifelse(touchscreen == "fallaci", 0, 1),
    household = as.numeric(household), 
    children = as.numeric(children),
    younger_children = as.numeric(younger_children)
  )  %>%
  select(-c(first_name, last_name, test_date, birth_date, comment))%>%
  #filter(!is.na(ageinyears))%>%
  rename(subjid = id)

```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_cong%>%
  filter(!subjid %in% tidy_data_cong$subjID)
# one child has no data, no idea where it is

# range of ages: should not be below 2.5
range(tidy_demographics_cong$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_cong$screen) 
unique(tidy_demographics_cong$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_cong%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_cong%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_cong%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_cong%>%filter(younger_children >= children) 
```

```{r}
data_cong <- tidy_demographics_cong%>%
  left_join(tidy_data_cong%>%rename_all(tolower),by = c("subjid"))%>%
  #mutate(community = "congo")%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```
# Uganda

```{r read_data}
# get all .json files
files <- list.files("../../raw_data/gafo-cc/uganda/", pattern = "*.json",recursive = T)%>% str_subset(pattern = "gafo--", negate = T)

# convert json files to tibbles
raw_data_uganda <- tibble()
for (f in files) {
  jf <- paste("../../raw_data/gafo-cc/uganda/", f, sep = "")
  jd <- jsonlite::fromJSON(paste(readLines(jf, warn = "FALSE"), collapse = ""))
  
  # needed because hedge trials have numbers, box trials have characters
  jd$targetPosition <- factor(as.character(jd$targetPosition))
  
  raw_data_uganda <- bind_rows(raw_data_uganda, jd)
}
# remove variables that we don't need anymore
rm(f, files, jf, jd)
```

```{r}
tidy_data_uganda <- raw_data_uganda %>%
  
  # convert all character vectors into factors
  
  mutate(
    
    # attention! the SVG coord system starts with 0, 0 in upper left corner
    # we transform the values so that 0, 0 is lower left corner (for plots etc)
    clickScaledY = 1080 - clickScaledY,
    targetY = 1080 - targetY, 
    targetCenterY = 1080 - targetCenterY, 
    eyeCenterRightY = 1080 - eyeCenterRightY,
    eyeCenterLeftY = 1080 - eyeCenterLeftY,
    pupilFinalRightY = 1080 - pupilFinalRightY,
    pupilFinalLeftY = 1080 - pupilFinalLeftY, 
    targetCentralityX = abs(960 - targetCenterX),
    
    # similarly here: in svg coords, negative click distance means up. 
    # here we invert it, so that negative values mean down
    clickDistFromTargetCenterY = clickDistFromTargetCenterY * -1, 
    clickDistFromTargetBBoxY = clickDistFromTargetBBoxY * -1, 
    
    # positive values for inward clicks (i.e.,towards the center), negative for outward clicks
    centralityBias = ifelse(targetCenterX <= 1920/2,
                            clickDistFromTargetCenterX, 
                            clickDistFromTargetCenterX*-1), 
    
    inwardClick = ifelse(centralityBias > 0, TRUE, FALSE), 
    
    # did the participant click on the right box?
    # also for hedge version, here we imagine a box surrounding the target center 
    # this way, we can compare hedge and box version ;) 
    boxWidth = 218, 
    boxBorderLeft = targetCenterX - boxWidth/2, 
    boxBorderRight = targetCenterX + boxWidth/2,
    correctBox = ifelse(boxBorderLeft <= clickScaledX & clickScaledX <= boxBorderRight, TRUE, FALSE), 
    
    datacollection = as.factor("in-person - supervised"), 
    sample = as.factor("na"),
    studytype = as.factor("vali")
  ) %>%
  mutate(subjID = ifelse(subjID == "ugaand04", "ugand004", subjID),
         subjID =as.factor(subjID))%>%
  select(-touchScreen)%>%
  mutate_if(is.character, as.factor)%>% 
  distinct(subjID, trialNr, .keep_all = T)#%>%select(subjID, population, trialType, trialNr, targetPosition, targetCentralityX, clickDistFromTargetCenterX)
```

```{r}
# quality checks

# range of click distance: min = 0; max = 1920
range(abs(tidy_data_uganda$clickDistFromTargetCenterX)) # 

# number of trials: everyone should have more than 4 trials.
tidy_data_uganda%>%group_by(subjID)%>%filter(voiceover == F, trialType == "test")%>%summarise(n = n())%>%filter(n<5) 

```

```{r demographics}
raw_demographics_uganda <- read_xlsx("../../raw_data/gafo-cc/uganda/gafo_uganda_participants_checked.xlsx", sheet = 1)

tidy_demographics_uganda <- raw_demographics_uganda %>%
  rename(subjid = id)%>%
  mutate_all(tolower)%>%
  filter(status == "keep")%>%
  mutate(
    test_date = as.Date(as.character(test_date), format = "%Y%m%d"),
    birth_date = as.Date(as.character(birth_date), format = "%Y%m%d"),
    ageinyears = as.numeric(difftime(test_date,birth_date, units = "days")/365.25),
    screen = as.numeric(screen), 
    touchscreen = as.numeric(touchscreen),
    household = as.numeric(household), 
    children = as.numeric(children),
    younger_children = as.numeric(younger_children)
  )  %>%
  select(-c(test_date, birth_date, comment, age))%>%
  filter(!is.na(ageinyears))

```

```{r}
# quality checks

# check for typos in subject names
tidy_demographics_uganda%>%
  filter(!subjid %in% tidy_data_uganda$subjID)

# one child is missing: ugand041

# range of ages: should not be below 2.5
range(tidy_demographics_uganda$ageinyears) 

# screen and touchscreen should only be 0 or 1 or NA
unique(tidy_demographics_uganda$screen) 
unique(tidy_demographics_uganda$touchscreen) 

# children should at least be 1 (the tested child) 
tidy_demographics_uganda%>%filter(children < 1)
# household should at least be 2 (the tested child and one adult) 
tidy_demographics_uganda%>%filter(household < 2) 
# household should be larger than children
tidy_demographics_uganda%>%filter(children >= household) 
# youngerchildren should be fewer than children
tidy_demographics_uganda%>%filter(younger_children >= children) 

```

```{r}
data_uganda <- tidy_demographics_uganda%>%
  left_join(tidy_data_uganda%>%rename_all(tolower),by = c("subjid"))%>%
  distinct(subjid, trialnr, .keep_all = TRUE)
```


# Merge
```{r}
merge_raw_data <- bind_rows(
  data_zambia,
  data_namibia%>%rename(younger_children = youngerchildren),
  data_leipzig,
  data_nigeria,
  data_plymouth,
  data_stanford,
  data_mex,
  data_china, 
  data_arg,
  data_ind,
  data_nz, 
  data_tur,
  data_cong,
  data_uganda
)%>%
 # mutate(community = paste0("c",as.character(as.numeric(as.factor(community)))))%>%
  filter(trialtype == "test",
         voiceover == F
         )%>%
  mutate(age_group = substr(ageinyears, 1,1), 
         trialnr = as.numeric(factor(trialnr)), 
         sex = ifelse(sex == "F", "f", sex),
         sex = ifelse(sex == "female", "f", sex),
         sex = ifelse(sex == "male", "m", sex),
         sex = ifelse(sex == "NaN", NA, sex), 
         screen = ifelse(touchscreen == 1, 1, screen),
         household = ifelse(household == "NaN", NA, household),
         children = ifelse(children == "NaN", NA, children),
         younger_children = ifelse(younger_children == "NaN", NA, younger_children))

```

# Quality checks

```{r}
# data checks

## communities
unique(merge_raw_data$community)

## age ranges
range(merge_raw_data$ageinyears)

## sex  
unique(merge_raw_data$sex)

## screen and touchscreen
unique(merge_raw_data$screen)
unique(merge_raw_data$touchscreen)
# check NAs
merge_raw_data%>%
  filter(is.na(screen), trialnr == 1)

merge_raw_data%>%
  filter(is.na(touchscreen), trialnr == 1)

### check if there are cases that say they don't have a screen but do say they have a touch screen 
merge_raw_data%>%
  filter(screen == 0 & touchscreen == 1, trialnr == 1)

# household
unique(merge_raw_data$household)

merge_raw_data%>%
  filter(is.na(household), trialnr == 1)

# children 
unique(merge_raw_data$children)
## check number of children - should include the one being tested, therefore cannot be 0
merge_raw_data%>%
  filter(children == 0, trialnr == 1)

## check if there are cases with more younger children than children (cannot be)

merge_raw_data%>%
  filter(children <= younger_children, trialnr == 1)

merge_raw_data%>%
  filter(children == younger_children, trialnr == 1)


```

```{r}
write_csv(merge_raw_data,"../data/gafo-cc-raw-data.csv")
```

```{r}
data <- merge_raw_data%>%
  select(subjid, community, age_group, ageinyears, sex, screen, touchscreen, household, children, younger_children, trialnr, targetposition,targetcenterx, targetcentralityx, clickdistfromtargetcenterx)%>%
  filter(ageinyears > 1)

write_csv(data,"../data/gafo-cc-clean-data.csv")


methods_data <- merge_raw_data%>%
  select(subjid, community, age_group, ageinyears, trialtype, voiceover, trialnr,screen, touchscreen, household, children, younger_children, targetposition,targetcentralityx, clickdistfromtargetcenterx)

write_csv(methods_data,"../../tango-cc-methods/data/data.csv")
```




```{r}
fam_excl <- bind_rows(
  data_zambia,
  data_namibia%>%rename(younger_children = youngerchildren),
  data_leipzig,
  data_nigeria,
  data_plymouth,
  data_stanford,
  data_mex,
  data_china, 
  data_arg,
  data_ind,
  data_nz, 
  data_tur,
  data_cong
)%>%
  filter(trialtype != "test")%>%
  group_by(subjid,community)%>%
  mutate(click = abs(clickdistfromtargetcenterx))%>%
  summarise(mean_click = mean(click))%>%
  filter(mean_click > 100)%>%
  pull(subjid)
```


```{r}
data <- read_csv("../data/gafo-cc-clean-data.csv")

data%>%
  #group_by(community)%>%
  summarise(n = n_distinct(subjid))

data%>%
  filter(touchscreen == 2)%>%
  distinct(subjid)

unique(data$screen)

unique(data$touchscreen)

unique(data$household)

unique(data$children)

unique(data$younger_children)
```



```{r}
data_arg%>%
  summarise(n= n_distinct(subjid))

data%>%
  group_by(community)%>%
  summarise(n= n_distinct(subjid))
```


```{r}
data%>%
  #select(-touchscreen)%>%
  filter(community == "hai||om" | community == "plymouth")%>%
  #rename(touchscreen = touchscreen.x)%>%
  group_by(subjid, community, sex, screen, touchscreen, household,children,younger_children, ageinyears)%>%
    summarise(precision = mean(abs(clickdistfromtargetcenterx)))%>%
  write_csv(.,"../data/gafo-cc-uk-namibia.csv")
```


# Data for model 

```{r}

communities <- unique(merge_raw_data$community)

for (i in communities) {
  
m_data <- merge_raw_data%>%
  filter(community == i,
         voiceover == F)%>%
  mutate(agecentered = ageinyears - min(ageinyears))%>%
  select(-c(sex,ageinyears, wrongareaclick, earlyclick, durationanimationballoontotal, durationanimationcomplete, responsetime, clientscreenwidth, clientscreenheight, clientscreenscaling, clickoriginalx, clickoriginaly, hitbbtargetx, hitbbtargety, clickdistfromtargetbboxx, clickedarea, studyversion, boxesnr,population, inhouse, os, mobile, browser, browserversion, safari, iossafari,target, voiceover, epoch, timestamp, inwardclick, boxwidth,boxborderleft, boxborderright , correctbox, datacollection, sample, studytype, comment, status, site,`location` ))

write(toJSON(m_data), file = paste0("../model/model_data/", i, "-model-data.json"))

#write_csv(mdata, file = "../model/model_data/", i, "-model-data.csv")

}



```


```{r}
mdata_small <- mdata%>%
  filter(subjid %in% c("VcyYgFQx", "k1mQYc2K", "niger007","niger057"))
  

write(toJSON(mdata_small), file = "../model/model_data/gafo-cc-model-data-small.json")
```

```{r}
prior <- dtruncnorm(seq(from = 0, to = 2900, by = 20), a = 1, b = 2920, mean = 1450, sd = 100)

length(prior)

write(toJSON(prior, digits = 4, use_signif = TRUE), file = "../model/model_data/centerBias_extended.json")
```

