---
title: "Gafo-cc visuals"
output: html_document
---

```{r}
library(tidyverse)
library(ggpubr)
library(ggthemes)
library(tidyboot)
library(maps)
library(brms)
library(cowplot)
```



```{r}
data <- read_csv("../data/gafo-cc-clean-data.csv")%>%
  mutate(continent = ifelse(
    community %in% c("leipzig", "plymouth"), "Europe", 
    ifelse(
      community %in% c("akure", "hai||om", "khwe", "chimfunshi", "bandongo", "bayaka", "windhoek", "uganda"), "Africa",
      ifelse(community %in% c("stanford", "mexico", "buenos_aires"), "America",
             ifelse(community %in% c("india", "beijing", "turkey"), "Asia", "Oceania"))
    )
  ))%>%
  mutate(continent = factor(continent, levels = c("America", "Africa", "Europe", "Asia", "Oceania"), ordered = T))%>%
  mutate(community = recode(community,
                            akure = "akure (nigeria)",
                            leipzig = "leipzig (germany)",
                            `hai||om` = "hai||om (namibia)",
                            khwe = "khwe (namibia)",
                            windhoek = "windhoek (namibia)",
                            stanford = "stanford (usa)",
                            chimfunshi = "chimfunshi (sambia)",
                            mexico = "ocuilan (mexico)",
                            plymouth = "plymouth (uk)",
                            beijing = "beijing (china)", 
                            india = "pune (india)",
                            buenos_aires = "buenos aires (argentina)",
                            auckland = "auckland (new zealand)",
                            turkey = "malatya (turkey)",
                            bandongo = "bandongo (rep. congo)",
                            bayaka = "bayaka (rep. congo)", 
                            uganda = "nyabyeya (uganda)"))
```
```{r}
# Population of the countries involved
(1394016000 + 1426093184 + 332639104	+ 214028304	+ 128649568 + 82017512 + 80159664 + 65761116 + 45479120 + 2630073	 + 43252968	 + 4925477	+ 17426624) /
8078229894 # proportion of world population 

```



```{r}
library(pals)

library(RColorBrewer)
qual_col_pals = brewer.pal.info[brewer.pal.info$colorblind == TRUE,]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

colors=kelly(n=n_distinct(data$community)+1)

colors <- colors[ !colors == '#F2F3F4']

```

```{r}
data%>%
  group_by(continent, community)%>%
  summarise(n= n_distinct(subjid))

data%>%
  summarise(n= n_distinct(subjid))

data%>%
  group_by(community, age_group)%>%
  summarise(n = n_distinct(subjid))
```



```{r}
data%>%
  group_by(continent, community,subjid, ageinyears)%>%
  summarise(impr = mean(abs(clickdistfromtargetcenterx)))%>%
  ggplot(aes(x = ageinyears, y = impr, col = community))+
  geom_point(alpha = .25)+
  geom_smooth(method = "glm")+
  scale_color_manual(name = "Community", values = colors)+
  ylim(0,1000)+
  facet_wrap(~continent)+
  #facet_wrap(~community)+
  labs(x = "Age (in years)", y ="Imprecision (average click distance from target)")+
  scale_x_continuous(breaks = 2:8)+
  theme_minimal()+
  theme(legend.position = "right")
  
```
```{r}
ggsave("../visuals/dev_site.png", width = 8, height = 6, bg = "white")
```


```{r}
data%>%
  group_by(targetcentralityx)%>%
  mutate(chance_upper = (targetcentralityx + 960)/2,
         chance_lower = -((targetcentralityx + 960)/2),
         center_lower = -targetcentralityx,
         center_upper = targetcentralityx)%>%
  ggplot(aes(x = targetcentralityx, y = clickdistfromtargetcenterx, col = community))+
  geom_hline(yintercept = 0, lty = 3, alpha = 0.75)+
  geom_line(aes(x = targetcentralityx, y = center_upper), lty = 1, alpha = .75, col = "firebrick")+
  geom_line(aes(x = targetcentralityx, y = center_lower), lty = 1, alpha = .75, col = "firebrick")+
  geom_line(aes(x = targetcentralityx, y = chance_upper), lty = 3, alpha = .75, col = "firebrick")+
  geom_line(aes(x = targetcentralityx, y = chance_lower), lty = 3, alpha = .75, col = "firebrick")+
  geom_point(pch = 1, alpha = 0.5)+
  scale_color_colorblind()+
  #ylim(-1500,1500)+
  theme_minimal()

```

```{r}
ggsave("../visuals/dev_site.png", width = 8, height = 6, bg = "white")
```

```{r}
data%>%
  distinct(targetposition, targetcentralityx)%>%
  expand_grid(random_click = runif(10000, min = 0, max = 1920))%>%
  mutate(dist = abs(targetcentralityx - random_click))%>%
  group_by(targetposition)%>%
  summarise(random = mean(dist))



```



```{r}
ptp<- data%>%
  #filter(community != "chimfunshi (sambia)")%>%
  mutate(targetposition = factor(targetposition, levels = c(1:10)))%>%
  #group_by(community, targetposition, age_group)%>%
  group_by(continent, community, targetposition)%>%
  tidyboot_mean(col= abs(clickdistfromtargetcenterx))


alt1 <- data%>%
  mutate(targetposition = factor(targetposition, levels = c(1:10)))%>%
  group_by(targetposition)%>%
  summarise(center = mean(targetcentralityx))%>%
  mutate(group = "group")%>%
  ungroup()

alt2 <- data%>%
  distinct(targetposition, targetcenterx)%>%
  expand_grid(random_click = runif(1000, min = 0, max = 1920))%>%
  mutate(dist = abs(targetcenterx - random_click))%>%
  group_by(targetposition)%>%
  summarise(random = mean(dist))%>%
  mutate(group = "group")

ggplot(ptp, aes(x = targetposition, y = mean, col = community))+
  #geom_line(data = alt1, aes(x = targetposition, y = center, group = group), lty = 3, alpha = 0.75, col = "black")+
  #geom_line(data = alt2, aes(x = targetposition, y = random, group = group), lty = 3, alpha = 0.75,  col = "black")+
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper),pch = 1, alpha = 0.75, position = position_dodge(width = .5))+
  labs(x = "Target position (binned)", y = "Imprecision (average click distance from target)")+
  scale_color_manual(name = "Community", values = colors)+
  facet_grid(~continent)+
  ylim(0,1000)+
  theme_minimal()
```

```{r}
ggsave("../visuals/target_position_site.png", width = 8, height = 6, bg = "white")
```


```{r}
ptp%>%
  select(community, targetposition, mean)%>%
  pivot_wider(names_from = targetposition, values_from = mean)%>%
  mutate(t1_vs_t10 = `1` - `10`,
         t2_vs_t9 = `2` - `9`,
         t3_vs_t8 = `3` - `8`,
         t4_vs_t7 = `4` - `7`,
         t5_vs_t6 = `5` - `6`)%>%
  select(community, t1_vs_t10, t2_vs_t9, t3_vs_t8, t4_vs_t7, t5_vs_t6)%>%
  pivot_longer(names_to = "side_bias", values_to = "value", cols = c(t1_vs_t10, t2_vs_t9, t3_vs_t8, t4_vs_t7, t5_vs_t6))%>%
  mutate(side_bias = factor(side_bias, levels = c("t1_vs_t10", "t2_vs_t9", "t3_vs_t8", "t4_vs_t7", "t5_vs_t6")))%>%
  ggplot(., aes(y = side_bias, x = value, col = community))+
    geom_vline(xintercept = 0, lty = 3, alpha = 0.75)+
    scale_color_manual(name = "Community", values = colors)+
    geom_point()+
    geom_path(aes(group = community))+
    labs(x = "Side bias (pos = better performance on right)", y = "Target position")+
    theme_minimal()
```



```{r}
ptp2<- data%>%
  #filter(community != "chimfunshi (sambia)")%>%
  mutate(targetposition = factor(targetposition, levels = c(1:10)))%>%
  #group_by(community, targetposition, age_group)%>%
  group_by(community,age_group, targetposition)%>%
  tidyboot_mean(col= abs(clickdistfromtargetcenterx))


ptp2%>%
  #filter(community == "leipzig (germany)")%>%
  ggplot(.,aes(x = targetposition, y = mean, col = community))+
  #geom_line(data = alt1, aes(x = targetposition, y = center, group = group), lty = 3, alpha = 0.75, col = "black")+
  #geom_line(data = alt2, aes(x = targetposition, y = random, group = group), lty = 3, alpha = 0.75,  col = "black")+
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper),pch = 1, alpha = 0.75, position = position_dodge(width = .5))+
  labs(x = "Target position (binned)", y = "Imprecision (average click distance from target)")+
  scale_color_manual(name = "Community", values = colors)+
  facet_grid(~factor(age_group))+
  ylim(0,1000)+
  theme_few()
```

```{r}
ggsave("../visuals/target_position_site_age.png", width = 12, height = 4, bg = "white", scale = 1.5)
```

```{r}
pscreen1 <- data%>%
  group_by(community)%>%
  mutate(clickdistfromtargetcenterx = scale(abs(clickdistfromtargetcenterx)))%>%
  mutate(screen = factor(screen),
         touchscreen = factor(touchscreen))%>%
  pivot_longer(cols = c(screen, touchscreen), names_to = "predictor", values_to = "value")%>%
  group_by(subjid, predictor, value)%>%
  summarise(mean= mean(clickdistfromtargetcenterx))

pscreen2 <- data%>%
  group_by(community)%>%
  mutate(clickdistfromtargetcenterx = scale(abs(clickdistfromtargetcenterx)))%>%
  mutate(screen = factor(screen),
         touchscreen = factor(touchscreen))%>%
  pivot_longer(cols = c(screen, touchscreen), names_to = "predictor", values_to = "value")%>%
  group_by(predictor, value)%>%
  tidyboot_mean(col= clickdistfromtargetcenterx)


ggplot(pscreen2%>%filter(!is.na(value)), aes(x = value, y = mean))+
  geom_jitter(data = pscreen1%>%filter(!is.na(value)), aes(x = value, y = mean), pch = 1, alpha = .25, height = 0)+
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), alpha = 0.75, position = position_dodge(width = .5), col = "firebrick")+
  facet_grid(~predictor, scales = "free_x")+
  scale_x_discrete(labels = c("no", "yes"))+
  labs(y = "Imprecision (scaled within community)", x = "Predictor value")+
  scale_color_colorblind()+
  
  #ylim(0,1000)+
  theme_bw()
```

```{r}
ggsave("../visuals/pred_screen.png", width = 8, height = 6, bg = "white")
```

```{r}
pred <- data%>%
  group_by(community)%>%
  mutate(clickdistfromtargetcenterx = scale(abs(clickdistfromtargetcenterx)), 
         household = scale(household), 
         children = scale(children),
         younger_children = scale(younger_children))%>%
  group_by(subjid,community, household, children, younger_children)%>%
  summarise(mean= mean(clickdistfromtargetcenterx))%>%
  pivot_longer(cols = c(household, children, younger_children), names_to = "predictor", values_to = "value")%>%
  group_by(predictor)%>%
  mutate(value = scale(value))
  


ggplot(pred, aes(x = value, y = mean))+
  geom_point(pch = 1)+
  geom_smooth(method = "glm")+
  facet_grid(~predictor, scales = "free_x")+
  stat_cor()+
  scale_color_colorblind()+
  labs(y = "Imprecision (scaled within community)", x = "Predictor value (scaled within community)")+
  #ylim(0,1000)+
  theme_bw()
```


```{r}
ggsave("../visuals/pred_household.png", width = 12, height = 6, bg = "white")
```


# Model based developmental trajectories

```{r}
ddata <- data%>%
  mutate(click = abs(clickdistfromtargetcenterx))%>%
  group_by(subjid, continent,community, ageinyears)%>%
  summarise(mean_click = mean(click))%>%
  ungroup()%>%
  mutate(ageinyears = ageinyears - min(ageinyears))

bm_base <- brm(mean_click ~ ageinyears + (ageinyears |community), 
                              data   = ddata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95))
```


```{r}
ndata <- ddata%>%
  distinct(continent, community, ageinyears)


post <- fitted(bm_base, newdata = ndata, re_formula =~(ageinyears|community))%>%
  as_tibble() %>%
  bind_cols(ndata)%>%
  mutate(ageinyears = ageinyears + min(data$ageinyears))


ggplot()+
  geom_point(data = ddata, aes(x = ageinyears+ min(data$ageinyears), y = mean_click, col = community), alpha = 0.25)+
  geom_smooth(data = post, aes(x = ageinyears, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_minimal()+
  scale_fill_manual(name = "Community", values = colors)+
  scale_color_manual(name = "Community", values = colors)+
  labs(x = "Age", y="Imprecision")+
  theme(legend.position = "right")+
  facet_wrap(~continent, nrow = 2)#+guides(col = "none", fill = "none")
```

```{r}
ggsave("../visuals/dev.png", width = 12, height = 8, bg = "white")
```

```{r}
am <- ggplot()+
  geom_point(data = ddata%>%filter(continent == "America"), aes(x = ageinyears+ min(data$ageinyears), y = mean_click, col = community), alpha = 0.25)+
  geom_smooth(data = post%>%filter(continent == "America"), aes(x = ageinyears, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_few()+
  scale_fill_colorblind(name = "")+
  scale_color_colorblind(name = "")+
  labs(x = "Age", y="Imprecision")+
  scale_x_continuous(limits = c(2,10))+
  scale_y_continuous(limits = c(0,1000))+
  theme(legend.position = c(0.7, 0.9), legend.background = element_blank(),axis.title.x = element_blank())+
  facet_wrap(~continent, nrow = 1)#+guides(col = "none", fill = "none")

af <- ggplot()+
  geom_point(data = ddata%>%filter(continent == "Africa"), aes(x = ageinyears+ min(data$ageinyears), y = mean_click, col = community), alpha = 0.25)+
  geom_smooth(data = post%>%filter(continent == "Africa"), aes(x = ageinyears, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_few()+
  scale_fill_colorblind(name = "")+
  scale_color_colorblind(name = "")+
  labs(x = "Age", y="Imprecision")+
    scale_x_continuous(limits = c(2,10))+
  scale_y_continuous(limits = c(0,1000))+
  theme(legend.position = "right", legend.background = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank())+
  facet_wrap(~continent, nrow = 1)#+guides(col = "none", fill = "none")
  
eu <- ggplot()+
  geom_point(data = ddata%>%filter(continent == "Europe"), aes(x = ageinyears+ min(data$ageinyears), y = mean_click, col = community), alpha = 0.25)+
  geom_smooth(data = post%>%filter(continent == "Europe"), aes(x = ageinyears, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_few()+
  scale_fill_colorblind(name = "")+
  scale_color_colorblind(name = "")+
  labs(x = "Age", y="Imprecision")+
    scale_x_continuous(limits = c(2,10))+
  scale_y_continuous(limits = c(0,1000))+
  theme(legend.position = c(0.7, 0.9), legend.background = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.x = element_blank())+
  facet_wrap(~continent, nrow = 1)#+guides(col = "none", fill = "none")
  
as <- ggplot()+
  geom_point(data = ddata%>%filter(continent == "Asia"), aes(x = ageinyears+ min(data$ageinyears), y = mean_click, col = community), alpha = 0.25)+
  geom_smooth(data = post%>%filter(continent == "Asia"), aes(x = ageinyears, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_few()+
  scale_fill_colorblind(name = "")+
  scale_color_colorblind(name = "")+
  labs(x = "Age", y="Imprecision")+
    scale_x_continuous(limits = c(2,10))+
  scale_y_continuous(limits = c(0,1000))+
  theme(legend.position = c(0.7, 0.9), legend.background = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.x = element_blank())+
  facet_wrap(~continent, nrow = 1)#+guides(col = "none", fill = "none")
  
oc <- ggplot()+
  geom_point(data = ddata%>%filter(continent == "Oceania"), aes(x = ageinyears+ min(data$ageinyears), y = mean_click, col = community), alpha = 0.25)+
  geom_smooth(data = post%>%filter(continent == "Oceania"), aes(x = ageinyears, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_few()+
  scale_fill_colorblind(name = "")+
  scale_color_colorblind(name = "")+
  labs(x = " ", y="Imprecision")+
    scale_x_continuous(limits = c(2,10))+
  scale_y_continuous(limits = c(0,1000))+
  theme(legend.position = c(0.7, 0.9), legend.background = element_blank(), )+
  facet_wrap(~continent, nrow = 1)#+guides(col = "none", fill = "none")
```

```{r}
plot_grid(
  plot_grid(am, eu, as,  nrow = 1),
  plot_grid(oc, af, NULL, rel_widths = c(0.975,1.45, 0.55), nrow = 1), nrow = 2, rel_heights = c(1,1.1) )
```
```{r}
ggsave("../visuals/dev_con.png", width = 14, height = 8, bg = "white", scale = 1)
```

# Predictors

```{r}
pred_agg_i <- data%>%
  mutate(older_children = children - 1 - younger_children)%>%
  group_by(community, subjid)%>%
  summarise(screen = mean(screen, na.rm = T),
            touchscreen = mean(touchscreen, na.rm = T), 
            older_children = mean(older_children, na.rm = T), 
            household = mean(household, na.rm = T))

pred_agg_g <- data%>%
  mutate(older_children = children - 1 - younger_children)%>%
  group_by(community)%>%
  summarise(screen = mean(screen, na.rm = T),
            touchscreen = mean(touchscreen, na.rm = T), 
            older_children = mean(older_children, na.rm = T), 
            household = mean(household, na.rm = T))%>%
  pivot_longer(names_to = "dem", values_to = "value", cols = c(screen, touchscreen, older_children, household))

pred_agg_g%>%
  filter(dem == "screen" | dem == "touchscreen")%>%
  ggplot(aes(y = community, x = dem, fill = value))+
  geom_point(pch = 22, size = 5, stroke = 0)+
  scale_fill_viridis_c()

pred_agg_g%>%
  filter(dem == "household" | dem == "older_children")%>%
  ggplot(aes(y = community, x = dem, fill = value))+
  geom_point(pch = 22, size = 5, stroke = 0)+
  scale_fill_viridis_c()


```

```{r}
pred_agg_perf <- data%>%
  mutate(older_children = children - 1 - younger_children)%>%
  group_by(community)%>%
  summarise(screen = mean(screen, na.rm = T),
            touchscreen = mean(touchscreen, na.rm = T), 
            older_children = mean(older_children, na.rm = T), 
            household = mean(household, na.rm = T), 
            perf = mean(abs(clickdistfromtargetcenterx)))

ggplot(pred_agg_perf, aes(x = perf, y = touchscreen))+
  geom_point()
```

# Map

```{r}
world <- map_data("world")
```


```{r}
data_map <- read_csv("../data/gafo-cc-clean-data.csv")%>%
  mutate(region = recode(community,
                            akure = "Nigeria",
                            leipzig = "Germany",
                            `hai||om` = "Namibia",
                            khwe = "Namibia",
                            windhoek = "Namibia",
                            stanford = "USA",
                            chimfunshi = "Zambia",
                            mexico = "Mexico",
                            plymouth = "UK",
                            beijing = "China",
                            india = "India",
                            buenos_aires = "Argentina",
                            auckland = "New Zealand",
                            turkey = "Turkey",
                            bandongo = "Republic of Congo",
                            bayaka = "Republic of Congo", 
                         uganda = "Uganda"))%>%
  mutate(loc_lat = recode(community,
                            akure = 7.251070,
                            leipzig = 51.339695,
                            `hai||om` = -18.771648361967873,
                            khwe = -17.95549,
                            windhoek = -22.560881,
                            stanford = 37.427475,
                            chimfunshi = -12.541857285496434,
                            mexico = 18.9802204332881, 
                            plymouth = 50.37469737043179,
                            beijing = 39.91475103408255, 
                            india = 18.5265350616402,
                            buenos_aires = -34.60217085665333,
                            auckland = -36.850146242932965,
                            turkey = 38.35501382975052, 
                            bandongo = 2.062200395167898,
                            bayaka = 3.5404910412941893, 
                            uganda = 1.6766777415592256))%>%
    mutate(loc_long = recode(community,
                            akure = 5.203540,
                            leipzig = 12.373075,
                            `hai||om` = 17.968581283099287,
                            khwe = 22.558622,
                            windhoek = 17.065756,
                            stanford = -122.169716,
                            chimfunshi = 27.85405941279387,
                            mexico = -99.41965213620936,
                            plymouth = -4.140423156946285,
                            beijing = 116.40832763995694, 
                            india = 73.86056457627757,
                            buenos_aires = -58.39139837939201,
                            auckland = 174.7651647587945, 
                            turkey = 38.33313216647862, 
                            bandongo = 17.000644575618752,
                            bayaka = 17.88784692818756,
                            uganda = 31.549794624310884))%>%
  group_by(community, loc_lat, loc_long, region)%>%
  summarise(Participants = n_distinct(subjid))


selWorld <- left_join(world, data_map, by = "region")%>%
  filter(region != "Antarctica")%>%
  mutate(fill = ifelse(is.na(Participants), "out", "in"))%>% 
  filter(! long > 180)
```
```{r}

plain <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5)
)

new_scale <- function(new_aes) {
  structure(ggplot2::standardise_aes_names(new_aes), class = "new_aes")
}

#' Convenient functions
new_scale_fill <- function() {
  new_scale("fill")
}

new_scale_color <- function() {
  new_scale("colour")
}

new_scale_colour <- function() {
  new_scale("colour")
}

#' Special behaviour of the "+" for adding a `new_aes` object
#' It changes the name of the aesthethic for the previous layers, appending
#' "_new" to them. 
ggplot_add.new_aes <- function(object, plot, object_name) {
  plot$layers <- lapply(plot$layers, bump_aes, new_aes = object)
  plot$scales$scales <- lapply(plot$scales$scales, bump_aes, new_aes = object)
  plot$labels <- bump_aes(plot$labels, new_aes = object)
  plot
}


bump_aes <- function(layer, new_aes) {
  UseMethod("bump_aes")
}

bump_aes.Scale <- function(layer, new_aes) {
  old_aes <- layer$aesthetics[remove_new(layer$aesthetics) %in% new_aes]
  new_aes <- paste0(old_aes, "_new")
  
  layer$aesthetics[layer$aesthetics %in% old_aes] <- new_aes
  
  if (is.character(layer$guide)) {
    layer$guide <- match.fun(paste("guide_", layer$guide, sep = ""))()
  }
  layer$guide$available_aes[layer$guide$available_aes %in% old_aes] <- new_aes
  layer
}

bump_aes.Layer <- function(layer, new_aes) {
  original_aes <- new_aes
  
  old_aes <- names(layer$mapping)[remove_new(names(layer$mapping)) %in% new_aes]
  new_aes <- paste0(old_aes, "_new")
  
  old_geom <- layer$geom
  
  old_setup <- old_geom$handle_na
  new_setup <- function(self, data, params) {
    colnames(data)[colnames(data) %in% new_aes] <- original_aes
    old_setup(data, params)
  }
  
  new_geom <- ggplot2::ggproto(paste0("New", class(old_geom)[1]), old_geom,
                               handle_na = new_setup)
  
  new_geom$default_aes <- change_name(new_geom$default_aes, old_aes, new_aes)
  new_geom$non_missing_aes <- change_name(new_geom$non_missing_aes, old_aes, new_aes)
  new_geom$required_aes <- change_name(new_geom$required_aes, old_aes, new_aes)
  new_geom$optional_aes <- change_name(new_geom$optional_aes, old_aes, new_aes)
  
  layer$geom <- new_geom
  
  old_stat <- layer$stat
  
  old_setup2 <- old_stat$handle_na
  new_setup <- function(self, data, params) {
    colnames(data)[colnames(data) %in% new_aes] <- original_aes
    old_setup2(data, params)
  }
  
  new_stat <- ggplot2::ggproto(paste0("New", class(old_stat)[1]), old_stat,
                               handle_na = new_setup)
  
  new_stat$default_aes <- change_name(new_stat$default_aes, old_aes, new_aes)
  new_stat$non_missing_aes <- change_name(new_stat$non_missing_aes, old_aes, new_aes)
  new_stat$required_aes <- change_name(new_stat$required_aes, old_aes, new_aes)
  new_stat$optional_aes <- change_name(new_stat$optional_aes, old_aes, new_aes)
  
  layer$stat <- new_stat
  
  layer$mapping <- change_name(layer$mapping, old_aes, new_aes)
  layer
}

bump_aes.list <- function(layer, new_aes) {
  old_aes <-  names(layer)[remove_new(names(layer)) %in% new_aes]
  new_aes <- paste0(old_aes, "_new")
  
  names(layer)[names(layer) %in% old_aes] <- new_aes
  layer
}

change_name <- function(list, old, new) {
  UseMethod("change_name")
}

change_name.character <- function(list, old, new) {
  list[list %in% old] <- new
  list
}

change_name.default <- function(list, old, new) {
  nam <- names(list)
  nam[nam %in% old] <- new
  names(list) <- nam
  list
}

change_name.NULL <- function(list, old, new) {
  NULL
}

remove_new <- function(aes) {
  stringi::stri_replace_all(aes, "", regex = "(_new)*")
}
```


```{r}
ggplot(data = selWorld, mapping = aes(x = long, y = lat, group = group)) + 
  coord_map("moll")+
  geom_polygon(aes(fill = fill)) +
  scale_fill_manual(breaks = c("out", "in"), values = c("grey", "#DBD56E"), guide = "none")+
  new_scale("fill") +
  geom_point(pch = 21, data = data_map, aes(x = loc_long, y = loc_lat, fill = Participants), col = "black", inherit.aes = F, size = 2.5, stroke = 0.5)+
  #scale_fill_distiller(palette ="RdBu", direction = -1) + # or direction=1
  scale_fill_viridis_c(direction = -1, guide = guide_colourbar(direction = "horizontal", title.position = "top", title.hjust = 0.5), name = "Sample size")+
  plain+
  theme(legend.position = c(0.15, 0.25), legend.background = element_blank())
```
```{r}
ggsave("../visuals/map.png", width = 12, height = 6, bg = "white")
```
