---
title: "Gafo-cc-analysis"
output: html_document
date: '2022-03-26'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidybayes)
library(ggthemes)
library(brms)
library(ggridges)
```


```{r}
exclude <- read_csv("../data/gafo-cc-clean-data.csv")%>%
  filter(children == younger_children, trialnr == 1)%>%
  pull(subjid)

mdata <- read_csv("../data/gafo-cc-clean-data.csv")%>%
  ungroup()%>%
  filter(!subjid %in% exclude)%>%
  mutate(older_children = children - 1 - younger_children)%>%
  mutate(ageinyears = scale(ageinyears),
         targetcentralityx = scale(targetcentralityx),
         trialnr = scale(trialnr),
         touchscreen = factor(touchscreen),
        screen = factor(screen),
        click = abs(clickdistfromtargetcenterx))%>%
  group_by(community)%>%
  mutate(children = scale(children),
         household = scale(household),
         younger_children = scale(younger_children),
         older_children = scale(older_children))%>%
  select(subjid,community,ageinyears,children, household, younger_children,older_children, trialnr, screen,touchscreen, targetcentralityx, click )




mdata%>%
  ggplot(aes(x = click))+
  geom_density()

```




```{r}
bm_int_id <- brm(click ~ ageinyears  * targetcentralityx + (targetcentralityx+trialnr|subjid) + (ageinyears * targetcentralityx |community),
                              data   = mdata,
                              family = Gamma(link = "log"),
                              warmup = 2000,
                              iter   = 6000,
                              chains = 4,
                              cores  = 4,
                 control = list(adapt_delta = 0.95),
                              backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))


bm_id <- brm(click ~ ageinyears  + targetcentralityx + (targetcentralityx|subjid) + (ageinyears |community), 
                              data   = mdata, 
                              family = Gamma(link = "log"),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

# bm_int <- brm(click ~ ageinyears  * targetcentralityx + (trialnr|subjid) + (ageinyears * targetcentralityx |community), 
#                               data   = mdata, 
#                               family = Gamma(link = "log"),
#                               warmup = 2000, 
#                               iter   = 6000, 
#                               chains = 4, 
#                               cores  = 4,
#               control = list(adapt_delta = 0.95),
#                               backend = "cmdstanr")%>%
#   add_criterion(., c("waic","loo"))
# 
bm_base <- brm(click ~ ageinyears  + targetcentralityx + (1|subjid) + (ageinyears |community),
                              data   = mdata,
                              family = Gamma(link = "log"),
                              warmup = 2000,
                              iter   = 6000,
                              chains = 4,
                              cores  = 4,
               control = list(adapt_delta = 0.95),
                              backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_fix <- brm(click ~ ageinyears  + targetcentralityx + (1|subjid) + (1 |community),
                              data   = mdata,
                              family = Gamma(link = "log"),
                              warmup = 2000,
                              iter   = 6000,
                              chains = 4,
                              cores  = 4,
               control = list(adapt_delta = 0.95),
                              backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))
# 
# bm_nage <- brm(click ~ targetcentralityx + (trialnr|subjid) + (1 |community), 
#                               data   = mdata, 
#                               family = Gamma(link = "log"),
#                               warmup = 2000, 
#                               iter   = 6000, 
#                               chains = 4, 
#                               cores  = 4,
#                control = list(adapt_delta = 0.95),
#                               backend = "cmdstanr")%>%
#   add_criterion(., c("waic","loo"))
# 
# bm_ntc <- brm(click ~ ageinyears  + (trialnr|subjid) + (ageinyears|community), 
#                               data   = mdata, 
#                               family = Gamma(link = "log"),
#                               warmup = 2000, 
#                               iter   = 6000, 
#                               chains = 4, 
#                               cores  = 4,
#               control = list(adapt_delta = 0.95),
#                               backend = "cmdstanr")%>%
#   add_criterion(., c("waic","loo"))

bm_co <- brm(click ~ 1 + (1|subjid)+ (1|community), 
                              data   = mdata, 
                              family = Gamma(link = "log"),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
               control = list(adapt_delta = 0.95),
                              backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_null <- brm(click ~ 1 + (1|subjid), 
                              data   = mdata, 
                              family = Gamma(link = "log"),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
               control = list(adapt_delta = 0.95),
                              backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))


loo_compare(bm_null,
            bm_co,
            #bm_ntc,
            #bm_nage,
            #bm_base,
            #bm_fix,
            #bm_int,
            #bm_id,
            #bm_int_id, 
            criterion = "loo")%>%as_tibble(rownames = "model")%>%left_join(
model_weights(bm_null,
            bm_co,
            #bm_ntc,
            #bm_nage,
            #bm_base,
            #bm_fix,
            #bm_int,
            #bm_id,
            #bm_int_id, 
            weights = "loo")%>%as_tibble(rownames = "model")%>%rename(waic_weight = value))

```

```{r}
plot(bm_int_id)

pp_check(bm_int_id)

```


```{r}
ndata <- mdata%>%
  distinct(community)%>%
  expand_grid(ageinyears = unique(mdata$ageinyears))%>%
  expand_grid(targetcentralityx = c(min(mdata$targetcentralityx),max(mdata$targetcentralityx)))


post <- fitted(bm_id, newdata = ndata, re_formula =~(ageinyears|community))%>%
  as_tibble() %>%
  bind_cols(ndata)%>%
  mutate(ageinyears = ageinyears + mean(data$ageinyears),
         targetcentralityx = factor(targetcentralityx, labels = c("middle","edge")))


ggplot()+
  geom_smooth(data = post, aes(x = ageinyears, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_bw()+
  scale_color_ptol(name = "Community")+
  scale_fill_ptol(name = "Community")+
  facet_grid(~targetcentralityx)+
  labs(x = "Age", y="Imprecision")


range(mdata$targetcentralityx)
```

```{r}
ndata <- mdata%>%
  distinct(community)%>%
  expand_grid(ageinyears = c(-1,0,1))%>%
  expand_grid(targetcentralityx = c(min(mdata$targetcentralityx),max(mdata$targetcentralityx)))


post <- fitted(bm_int_id, newdata = ndata, re_formula =~(targetcentralityx|community))%>%
  as_tibble() %>%
  bind_cols(ndata)


ggplot()+
  geom_smooth(data = post, aes(x = targetcentralityx, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_bw()+
  scale_color_ptol(name = "Community")+
  scale_fill_ptol(name = "Community")+
  facet_grid(~ageinyears)+
  labs(x = "Target centrality", y="Imprecision")


range(mdata$ageinyears)
```



```{r}
ps <- bm_int_id%>%posterior_samples()%>%
  select(b_targetcentralityx, contains("targetcentralityx") & starts_with("r_community"))%>%
  select(!contains("ageinyears"))%>%
  pivot_longer(cols = c(-b_targetcentralityx), names_to = "site", values_to = "value")%>%
  mutate(site= str_remove(site,"r_community"),
         site= str_remove(site,"Intercept"),
         site= str_remove(site,"targetcentralityx"),
         site= str_remove(site,"\\["),
         site= str_remove(site,"\\]"),
         site= str_remove(site,"\\,"))%>%
  mutate(est = value + b_targetcentralityx)

ggplot(ps,aes(y = site, x = est)) +
 stat_halfeye(alpha = .7, .width = c(.95, .80)) +
    labs(x = "Posterior estimate", y ="")+
  guides(fill = "none")+
  #facet_grid(~type, scales = "free_x")+
  #geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw()
```
```{r}
ps <- bm_int_id%>%posterior_samples()%>%
  select("b_Intercept", "b_targetcentralityx",starts_with("r_community"))%>%
  pivot_longer(cols = c(3:50), names_to = "site", values_to = "value")%>%
  mutate(type = ifelse(grepl("Intercept", site), "intercept", "age"),
         site= str_remove(site,"r_community"),
         site= str_remove(site,"Intercept"),
         site= str_remove(site,"ageinyears"),
         site= str_remove(site,"\\["),
         site= str_remove(site,"\\]"),
         site= str_remove(site,"\\,"))%>%
  pivot_longer(cols = c(b_Intercept, b_ageinyears), names_to = "fix_param", values_to = "fix_value")%>%
  mutate(fix_param= tolower(str_remove(fix_param,"b_")),
         fix_param = ifelse(fix_param == "ageinyears", "age", fix_param))%>%
  filter(type == fix_param)%>%
  mutate(est = value + fix_value)

ggplot(ps,aes(y = site, x = est)) +
 stat_halfeye(alpha = .7, .width = c(.95, .80)) +
    labs(x = "Posterior estimate", y ="")+
  guides(fill = "none")+
  facet_grid(~type, scales = "free_x")+
  #geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw()
```


# Screens

```{r}
sdata <- mdata%>%
  group_by(subjid, ageinyears,community,screen, touchscreen)%>%
  summarise(mean_click = mean(click))%>%
  group_by(community)%>%
  mutate(mean_click = scale(mean_click))%>%
  na.omit()


```

```{r}
bm_s_base <- brm(mean_click ~ ageinyears  + (ageinyears |community), 
                              data   = sdata, 
                              family = "Gaussian",
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))


bm_s_s_fix <- brm(mean_click ~ ageinyears  + screen + (ageinyears |community), 
                              data   = sdata, 
                              family = "Gaussian",
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_s_s_rand <- brm(mean_click ~ ageinyears  + screen + (ageinyears + screen|community), 
                              data   = sdata, 
                              family = "Gaussian",
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_s_ts_fix <- brm(mean_click ~ ageinyears  + touchscreen + (ageinyears |community), 
                              data   = sdata, 
                              family = "Gaussian",
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_s_ts_rand <- brm(mean_click ~ ageinyears  + touchscreen + (ageinyears + touchscreen|community), 
                              data   = sdata, 
                              family = "Gaussian",
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))
```


```{r}
loo_compare(bm_s_base,
            bm_s_s_fix,
            bm_s_s_rand,
            bm_s_ts_fix,
            bm_s_ts_rand
            )%>%as_tibble(rownames = "model")%>%left_join(
model_weights(bm_s_base, bm_s_s_fix,
            bm_s_s_rand,
            bm_s_ts_fix,
            bm_s_ts_rand,
            weights = "waic")%>%as_tibble(rownames = "model")%>%rename(waic_weight = value))
```


# Household demographics

```{r}
cdata <- mdata%>%
  group_by(subjid, community, ageinyears, children, household, younger_children)%>%
  summarise(mean_click = mean(click))%>%
  group_by(community)%>%
  mutate(children = scale(children), 
         household = scale(household), 
         younger_children = scale(younger_children), 
         #mean_click = scale(mean_click)
         )%>%
  na.omit()


ggplot(cdata, aes(x = mean_click))+
  geom_density()
```

```{r}
bm_dem_base <- brm(mean_click ~ ageinyears  + (ageinyears |community), 
                              data   = cdata, 
                              lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))


bm_dem_hh_fix <- brm(mean_click ~ ageinyears  + household + (ageinyears |community), 
                              data   = cdata, 
                              family = Gamma(link = "log"),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_dem_hh_rand <- brm(mean_click ~ ageinyears  + household + (ageinyears + household|community), 
                              data   = cdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_dem_hh_rand_int <- brm(mean_click ~ ageinyears  * household + (ageinyears * household|community), 
                              data   = cdata, 
                              lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))


bm_dem_c_fix <- brm(mean_click ~ ageinyears  + children + (ageinyears |community), 
                              data   = cdata, 
                              lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_dem_c_rand <- brm(mean_click ~ ageinyears  + children + (ageinyears + children|community), 
                              data   = cdata, 
                              lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_dem_yc_fix <- brm(mean_click ~ ageinyears  + younger_children + (ageinyears |community), 
                              data   = cdata, 
                              lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

bm_dem_yc_rand <- brm(mean_click ~ ageinyears  + younger_children + (ageinyears + younger_children|community), 
                              data   = cdata, 
                              lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

```




```{r}

loo_compare(bm_dem_base,
            bm_dem_hh_fix,
            bm_dem_hh_rand,
            #bm_dem_hh_rand_int,
            bm_dem_c_fix,
            bm_dem_c_rand,
            bm_dem_yc_fix#,
            #bm_dem_yc_rand
            )%>%as_tibble(rownames = "model")%>%left_join(
model_weights(bm_dem_base,
            bm_dem_hh_fix,
            bm_dem_hh_rand,
            #bm_dem_hh_rand_int,
            bm_dem_c_fix,
            bm_dem_c_rand,
            bm_dem_yc_fix,
            #bm_dem_yc_rand,
            weights = "waic")%>%as_tibble(rownames = "model")%>%rename(waic_weight = value))
```
```{r}
ncdata <- cdata%>%
  distinct(community)%>%
  expand_grid(ageinyears = 0)%>%
  expand_grid(household = c(min(cdata$household):max(cdata$household)))


cpost <- fitted(bm_dem_hh_fix, newdata = ncdata, re_formula =~(1|community))%>%
  as_tibble() %>%
  bind_cols(ncdata)


ggplot()+
  geom_smooth(data = cpost, aes(x = household, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_bw()+
  scale_color_ptol(name = "Community")+
  scale_fill_ptol(name = "Community")+
  facet_grid(~ageinyears)+
  labs(x = "Household size (scaled)", y="Imprecision")


range(mdata$targetcentralityx)
```
```{r}
ncdata <- cdata%>%
  distinct(community)%>%
  expand_grid(ageinyears = 0)%>%
  expand_grid(household = c(min(cdata$household):max(cdata$household)))


cpost <- fitted(bm_dem_hh_rand, newdata = ncdata, re_formula =~(household|community))%>%
  as_tibble() %>%
  bind_cols(ncdata)


ggplot()+
  geom_smooth(data = cpost, aes(x = household, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_bw()+
  scale_color_ptol(name = "Community")+
  scale_fill_ptol(name = "Community")+
  facet_grid(~community)+
  labs(x = "Household size (scaled)", y="Imprecision")

```

```{r}
as_draws_df(bm_dem_hh_rand)%>%
  select(contains("household"))%>%
  pivot_longer(cols = contains("household]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_household)%>%
  ggplot(aes(x= post, y = community))+
  stat_slabinterval()+
  theme_bw()
```


# Household and screens

```{r}
scdata <- mdata%>%
  filter(!subjid %in% exclude)%>%
  group_by(subjid, community, ageinyears, touchscreen, household, children, younger_children)%>%
  summarise(mean_click = mean(click))%>%
  mutate(older_children = children - 1 - younger_children)%>%
  ungroup()%>%
  group_by(community)%>%
  mutate(
         household = scale(household), 
         children = scale(children), 
         older_children = scale(older_children),
         younger_children = scale(younger_children)
         )%>%
  na.omit()

```

```{r}
bm_base <- brm(mean_click ~ ageinyears + (ageinyears |community), 
                              data   = scdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr",
             threads = threading(2)
             )%>%
  add_criterion(., c("waic","loo"))

bm_tc <- brm(mean_click ~ ageinyears + touchscreen + (ageinyears |community), 
                              data   = scdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr",
             threads = threading(2))%>%
  add_criterion(., c("waic","loo"))

bm_tc_hh <- brm(mean_click ~ ageinyears + touchscreen + household + (ageinyears |community), 
                              data   = scdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr",
             threads = threading(2)
             )%>%
  add_criterion(., c("waic","loo"))


bm_tc_c <- brm(mean_click ~ ageinyears + touchscreen + children + (ageinyears |community), 
                              data   = scdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr",
             threads = threading(2)
             )%>%
  add_criterion(., c("waic","loo"))

bm_tc_yc <- brm(mean_click ~ ageinyears + touchscreen + younger_children + (ageinyears |community), 
                              data   = scdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr",
             threads = threading(2)
             )%>%
  add_criterion(., c("waic","loo"))

bm_tc_oc <- brm(mean_click ~ ageinyears + touchscreen + older_children + (ageinyears |community), 
                              data   = scdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr",
             threads = threading(2)
             )%>%
  add_criterion(., c("waic","loo"))

bm_tc_oc_rand <- brm(mean_click ~ ageinyears + touchscreen + older_children + (touchscreen + older_children + ageinyears |community), 
                              data   = scdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 4000, 
                              chains = 4, 
                              cores  = 4,
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr",
             threads = threading(2)
             )%>%
  add_criterion(., c("waic","loo"))
```


```{r}
loo_compare(bm_base,
            bm_tc,
            bm_tc_hh,
            bm_tc_oc,
            bm_tc_yc,
            bm_tc_c,
            bm_tc_oc_rand,
            criterion = "waic"
            )%>%as_tibble(rownames = "model")

model_weights(bm_base,
            bm_tc,
            bm_tc_hh,
            bm_tc_oc,
            bm_tc_yc,
            bm_tc_c,
            bm_tc_oc_rand,
            criterion = "waic")%>%as_tibble(rownames = "model")
```
```{r}
ndata <- scdata%>%
  distinct(community, ageinyears)


post <- fitted(bm_base, newdata = ndata, re_formula =~(ageinyears|community))%>%
  as_tibble() %>%
  bind_cols(ndata)%>%
  mutate(ageinyears = ageinyears + mean(data$ageinyears))


ggplot()+
  geom_smooth(data = post, aes(x = ageinyears, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_bw()+
  scale_color_manual(name = "Community", values = colors)+
  scale_fill_manual(name = "Community", values = colors)+
  labs(x = "Age", y="Imprecision")#+
  facet_wrap(~community)+guides(col = "none", fill = "none")
```


```{r}
pssc <- bm_octs_fix%>%posterior_samples()%>%
  select("b_ageinyears","b_touchscreen1", "b_older_children")%>%
  pivot_longer(cols = everything(), names_to = "parameter", values_to = "value")%>%
  mutate(parameter= tolower(str_remove(parameter,"b_")))

ggplot(pssc,aes(y = parameter, x = value)) +
 stat_halfeye(alpha = .7, .width = c(.95, .89)) +
    labs(x = "Posterior estimate", y ="")+
  guides(fill = "none")+
  #facet_grid(~type, scales = "free_x")+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw()
```

```{r}
as_draws_df(bm_octs_rand)%>%
  select(contains("children"))%>%
  select(contains("children"))%>%
  pivot_longer(cols = contains("children]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_older_children, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",older_children]"),
         community = str_remove(community, "\\["))%>%
  ggplot(aes(x= post, y = community))+
  geom_vline(xintercept = 0, lty = 3, alpha = 0.75)+
  geom_density_ridges(rel_min_height = 0.01, col = "white", alpha = .75)+
  #stat_pointinterval()+
  #xlim(-0.15, 0.1)+
  theme_bw()

as_draws_df(bm_octs_rand)%>%
  select(contains("touchscreen"))%>%
  select(contains("touchscreen"))%>%
  pivot_longer(cols = contains("touchscreen1]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_touchscreen1, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",touchscreen1]"),
         community = str_remove(community, "\\["))%>%
  ggplot(aes(x= post, y = community))+
  geom_vline(xintercept = 0, lty = 3, alpha = 0.75)+
  geom_density_ridges(rel_min_height = 0.01, col = "white", alpha = .75)+
  #stat_pointinterval()+
  #xlim(-0.15, 0.1)+
  theme_bw()

as_draws_df(bm_octs_rand)%>%
  select(contains("ageinyears"))%>%
  select(contains("ageinyears"))%>%
  pivot_longer(cols = contains("ageinyears]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_ageinyears, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",ageinyears]"),
         community = str_remove(community, "\\["))%>%
  ggplot(aes(x= post, y = community))+
  geom_vline(xintercept = 0, lty = 3, alpha = 0.75)+
  geom_density_ridges(rel_min_height = 0.01, col = "white", alpha = .75)+
  #stat_pointinterval()+
  #xlim(-0.15, 0.1)+
  theme_bw()

bind_rows(
as_draws_df(bm_octs_rand)%>%
  select(contains("children"))%>%
  select(contains("children"))%>%
  pivot_longer(cols = contains("children]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_older_children, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",older_children]"),
         community = str_remove(community, "\\["))%>%
  select(community, post)%>%
  mutate(type = "older_children"), 

as_draws_df(bm_octs_rand)%>%
  select(contains("touchscreen"))%>%
  select(contains("touchscreen"))%>%
  pivot_longer(cols = contains("touchscreen1]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_touchscreen1, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",touchscreen1]"),
         community = str_remove(community, "\\["))%>%
  select(community, post)%>%
  mutate(type = "touchscreen"),

as_draws_df(bm_octs_rand)%>%
  select(contains("ageinyears"))%>%
  select(contains("ageinyears"))%>%
  pivot_longer(cols = contains("ageinyears]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_ageinyears, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",ageinyears]"),
         community = str_remove(community, "\\["))%>%
  select(community, post)%>%
  mutate(type = "ageinyears")

)%>%
  ggplot(aes(x= post, y = community))+
  geom_density_ridges(rel_min_height = 0.005, col = "black", alpha = .75, fill = NA)+
  geom_vline(xintercept = 0, lty = 3)+
  facet_grid(~type, scales = "free_x")+
  #stat_pointinterval(size = 0.1)+
  #xlim(-0.15, 0.1)+
  theme_minimal()+
  theme(panel.border = element_rect(colour = "black", fill=NA, size = .5))
  
```

```{r}
ncdata <- scdata%>%
  distinct(community)%>%
  expand_grid(ageinyears = 0)%>%
  mutate(touchscreen = 1)%>%
  expand_grid(older_children = c(min(scdata$older_children):max(scdata$older_children)))


cpost <- fitted(bm_octs_rand, newdata = ncdata, re_formula =~(older_children|community))%>%
  as_tibble() %>%
  bind_cols(ncdata)


ggplot()+
  geom_smooth(data = cpost, aes(x = older_children, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =community, col = community), stat = "identity", alpha = .25)+
  theme_bw()+
  scale_color_manual(name = "Community", values = colors)+
  scale_fill_manual(name = "Community", values = colors)+
  facet_wrap(~community, nrow = 2)+
  labs(x = "No of children older than the target child (scaled)", y="Imprecision")

```


```{r}
ncdata <- scdata%>%
  distinct(community)%>%
  expand_grid(ageinyears = c(-1, 0, 1))%>%
  mutate(touchscreen = 1)%>%
  expand_grid(older_children = c(min(scdata$older_children):max(scdata$older_children)))


cpost <- fitted(bm_octs_rand_int, newdata = ncdata, re_formula =~(older_children|community))%>%
  as_tibble() %>%
  bind_cols(ncdata)


ggplot()+
  geom_smooth(data = cpost, aes(x = older_children, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = factor(ageinyears), col = factor(ageinyears)), stat = "identity", alpha = .25)+
  theme_bw()+
  scale_color_ptol()+
  scale_fill_ptol()+
  facet_wrap(~community, nrow = 2)+
  labs(x = "No of children older than the target child (scaled)", y="Imprecision")

```


```{r}
ggsave("../visuals/old_child_site.png", width = 12, height = , bg = "white")
```


# Trial level analysis

```{r}
bm_trial_base <- brm(click ~ targetcentralityx + ageinyears + (targetcentralityx|subjid)+ (ageinyears + targetcentralityx |community),
                              data   = mdata%>%na.omit(), 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
                              threads = threading(8),
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

saveRDS(bm_trial_base, "../saves/bm_trial_base.rds")

bm_trial_pred <- brm(click ~ targetcentralityx + ageinyears + touchscreen + older_children + (targetcentralityx|subjid)+ (ageinyears + touchscreen + older_children + targetcentralityx |community),
                              data   = mdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
                              threads = threading(8),
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")%>%
  add_criterion(., c("waic","loo"))

saveRDS(bm_trial_pred, "../saves/bm_trial_pred.rds")


loo_compare(bm_trial_base,
            bm_trial_pred
            )%>%as_tibble(rownames = "model")

fixef(bm_trial_pred)
```

```{r}
draws <- bind_rows(
as_draws_df(bm_trial_pred)%>%
  select(contains("children"))%>%
  select(contains("children"))%>%
  select(-contains("sd"))%>%
  select(-contains("cor"))%>%
  pivot_longer(cols = contains("children]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_older_children, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",older_children]"),
         community = str_remove(community, "\\["))%>%
  select(community, post)%>%
  mutate(type = "older_children"), 

as_draws_df(bm_trial_pred)%>%
  select(contains("touchscreen"))%>%
  select(contains("touchscreen"))%>%
  select(-contains("sd"))%>%
  select(-contains("cor"))%>%
  pivot_longer(cols = contains("touchscreen1]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_touchscreen1, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",touchscreen1]"),
         community = str_remove(community, "\\["))%>%
  select(community, post)%>%
  mutate(type = "touchscreen"),

as_draws_df(bm_trial_pred)%>%
  select(contains("ageinyears"))%>%
  select(contains("ageinyears"))%>%
  select(-contains("sd"))%>%
  select(-contains("cor"))%>%
  pivot_longer(cols = contains("ageinyears]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_ageinyears, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",ageinyears]"),
         community = str_remove(community, "\\["))%>%
  select(community, post)%>%
  mutate(type = "ageinyears"),

as_draws_df(bm_trial_pred)%>%
  select(contains("targetcentralityx"))%>%
  select(contains("targetcentralityx"))%>%
  select(-contains("sd"))%>%
  select(-contains("cor"))%>%
  select(-contains("subjid"))%>%
  pivot_longer(cols = contains("targetcentralityx]"), names_to = "community", values_to = "value")%>%
  mutate(post = value + b_targetcentralityx, 
         community = str_remove(community, "r_community"),
         community = str_remove(community, ",targetcentralityx]"),
         community = str_remove(community, "\\["))%>%
  select(community, post)%>%
  mutate(type = "targetcentrality")

)

pdraws <- draws%>%
  mutate(continent = ifelse(
    community %in% c("leipzig", "plymouth"), "Europe", 
    ifelse(
      community %in% c("akure", "hai||om", "khwe", "chimfunshi", "bandongo", "bayaka", "windhoek", "uganda"), "Africa",
      ifelse(community %in% c("stanford", "mexico", "buenos_aires"), "America",
             ifelse(community %in% c("india", "beijing", "turkey"), "Asia", "Oceania"))
    )
  ))%>%
  mutate(continent = factor(continent, levels = c("America", "Africa", "Europe", "Asia", "Oceania"), ordered = T))%>%
  mutate(community = recode(community,
                            akure = "Akure (Nigeria)",
                            leipzig = "Leipzig (Germany)",
                            `hai||om` = "Hai||om (Namibia)",
                            khwe = "Khwe (Namibia)",
                            windhoek = "Windhoek (Namibia)",
                            stanford = "Stanford (USA)",
                            chimfunshi = "Chimfunshi (Sambia)",
                            mexico = "Ocuilan (Mexico)",
                            plymouth = "Plymouth (UK)",
                            beijing = "Beijing (China)", 
                            india = "Pune (India)",
                            buenos_aires = "Buenos Aires (Argentina)",
                            auckland = "Auckland (New Zealand)",
                            turkey = "Malatya (Turkey)",
                            bandongo = "Bandongo (Rep. Congo)",
                            bayaka = "Bayaka (Rep. Congo)", 
                            uganda = "Nyabyeya (Uganda)"))

saveRDS(pdraws, "../saves/pdraws.rds")

pdraws <- readRDS("../saves/pdraws.rds")

ggplot(pdraws, aes(x= post, y = community))+
  #geom_density_ridges(rel_min_height = 0.005, col = "black", alpha = .75, fill = NA)+
  geom_density_ridges(rel_min_height = 0.005, col = "white", alpha = .75, fill = "grey")+
  geom_vline(xintercept = 0, lty = 3)+
  facet_grid(continent~type, scales = "free", space = "free_y")+
  #stat_pointinterval(size = 0.1)+
  #xlim(-0.15, 0.1)+
  theme_minimal()+
  theme(panel.border = element_rect(colour = "black", fill=NA, size = .5))

```


# Cross-validation

```{r}

bm_null <- brm(click ~ targetcentralityx + (targetcentralityx|subjid),
                              data   = mdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
                              threads = threading(8),
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")

bm_age <- brm(click ~ targetcentralityx + ageinyears + (targetcentralityx|subjid),
                              data   = mdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
                              threads = threading(8),
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")

bm_cult <- brm(click ~ targetcentralityx + (targetcentralityx|subjid)+ (targetcentralityx |community),
                              data   = mdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
                              threads = threading(8),
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")


bm_cult_age <- brm(click ~ targetcentralityx + ageinyears + (targetcentralityx|subjid)+ (ageinyears + targetcentralityx |community),
                              data   = mdata, 
                              family = lognormal(),
                              warmup = 2000, 
                              iter   = 6000, 
                              chains = 4, 
                              cores  = 4,
                              threads = threading(8),
             control = list(adapt_delta = 0.95),
             backend = "cmdstanr")
```


```{r}
six_fold_cross_validation <- function(data, m1, m2, m3, m4, repeats) {

  
  N_ids = n_distinct(data$subjid)
#Prepare results DF
  results <- tibble(
    m1_score=numeric(), 
    m2_score=numeric() , 
    m3_score=numeric(),
    m4_score=numeric(),
    
    m4_beats_m3=logical(),
    m4_beats_m2=logical(),
    m4_beats_m1=logical(),
    
    m3_beats_m2=logical(),
    m3_beats_m1=logical(),
    
    m2_beats_m1=logical(), 
    
    m1 = character(), 
    m2 = character(),
    m3 = character(),
    m4 = character())
 

#Repeat the whole shebang several times
  for(i in 1:repeats) {

  # Split dataset into 6 bins
  bin_data <- data%>%group_by(community)%>%distinct(subjid) %>% mutate(bin = rep(1:6, length.out = n()))

for(j in 1:6) {
    # Use bin j as "hold out" data
    testing_ids <- bin_data%>%filter(bin == j)%>%pull(subjid)
    training_ids <- bin_data%>%filter(bin != j)%>%pull(subjid)
    # Safety check - is partition complete and disjoint?
    stopifnot(length(testing_ids) + length(training_ids) == N_ids)
    stopifnot(length(intersect(testing_ids, training_ids)) == 0)
# Create two separate dataframes
    testing_data <- filter(data, subjid %in% testing_ids)
    training_data <- filter(data, subjid %in% training_ids)

    # Train models
    up_m1 <- update(m1, newdata=training_data, cores=4, threads = threading(8),backend = "cmdstanr")
    up_m2 <- update(m2, newdata=training_data, cores=4, threads = threading(8),backend = "cmdstanr")
    up_m3 <- update(m3, newdata=training_data, cores=4, threads = threading(8),backend = "cmdstanr")
    up_m4 <- update(m4, newdata=training_data, cores=4, threads = threading(8),backend = "cmdstanr")

    # Sample predictions
    preds_m1 <- posterior_predict(up_m1, newdata=testing_data, allow_new_levels=TRUE, sample_new_levels="gaussian")
    preds_m2 <- posterior_predict(up_m2, newdata=testing_data, allow_new_levels=TRUE, sample_new_levels="gaussian")
    preds_m3 <- posterior_predict(up_m3, newdata=testing_data, allow_new_levels=TRUE, sample_new_levels="gaussian")
    preds_m4 <- posterior_predict(up_m4, newdata=testing_data, allow_new_levels=TRUE, sample_new_levels="gaussian")

    # Evaluate predictive accuracy
  score_m1 <- mean(sqrt(colMeans((testing_data$click - t(preds_m1))**2)))
  score_m2 <- mean(sqrt(colMeans((testing_data$click - t(preds_m2))**2)))
  score_m3 <- mean(sqrt(colMeans((testing_data$click - t(preds_m3))**2)))
  score_m4 <- mean(sqrt(colMeans((testing_data$click - t(preds_m4))**2)))

  m1_name <-  as.character(substitute(m1))
  m2_name <-  as.character(substitute(m2))
  m3_name <-  as.character(substitute(m3))
  m4_name <-  as.character(substitute(m4))
  
    # Record results
    results <- add_row(repeats = i,
                       fold = j, 
                       results,
                       m1_score = score_m1, 
                       m2_score = score_m2, 
                       m3_score = score_m3,
                       m4_score = score_m4,

                       m4_beats_m3 = m4_score < m3_score,
                       m4_beats_m2 = m4_score < m2_score,
                       m4_beats_m1 = m4_score < m1_score,
                       
                       m3_beats_m2 = m3_score < m2_score,
                       m3_beats_m1 = m3_score < m1_score,
                       m2_beats_m1 = m2_score < m1_score, 
                       
                       m1  = m1_name, 
                       m2 = m2_name, 
                       m3 = m3_name,
                       m4 = m4_name)
 }
  }
  return(results)
}
```

## Test for importance of culture and effect of age 

```{r}
cv_cult <- six_fold_cross_validation(mdata, bm_null, bm_cult, bm_age, bm_cult_age, bm_cult_x_age, 2)
```

```{r}
mean(cv_cult$m4_beats_m1)
```

